CREATE DATABASE EmailsServiceDb
GO

USE EmailsServiceDb
GO
CREATE TABLE Emails
(
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	WasSended BIT DEFAULT 0,
	[From] NVARCHAR(MAX) NOT NULL,
	DisplayName NVARCHAR(MAX),
	[To] NVARCHAR(MAX) NOT NULL,
	Bcc NVARCHAR(MAX),
	CC NVARCHAR(MAX),
	ReplyTo NVARCHAR(MAX) NOT NULL,
	ReplyToName NVARCHAR(MAX),
	Subject NVARCHAR(MAX) NOT NULL,
	Body NVARCHAR(MAX) NOT NULL,
	Trial int DEFAULT 0 NOT NULL
)
